### PR TITLE
Update dependency-injection.md for provider object && @Injectable

### PR DESCRIPTION
**Pull request by kesslerdev**

### CODE REVIEW

**Comment by ardatan** [comment]
You still have to use `Injectable` decorator if you want to benefit from metadata reflection instead of using `@Inject()` manually. So I think this won't be a correct information.

**Comment by kesslerdev** [comment]
this precision is due to [injector.provide method](https://github.com/Urigo/graphql-modules/blob/master/packages/di/src/injector.ts#L74), it dont use class metadata if argument is an object with `provide`

**Comment by ardatan** [comment]
@kesslerdev Yes but we cannot say `useClass` is for the classes which don't have `DI` inside of them because without `useClass`, we also support that.

**Comment by kesslerdev** [comment]
I'm using only JS  `@graphql-modules/di@0.7.8`
```js
// provider.js
class MyProvider{
}
module.exports = Injectable({ scope: ProviderScope.Session })(MyProvider)

```

```js
// module.js
module.exports = new GraphQLModule({
  providers: [
    {
      provide: 'myprovider',
      useClass: MyProvider,
    },
  ],
})
```

with this code the provider `myprovider` are in `ProviderScope.Application` not `ProviderScope.Session`

when i refactor a part of my app i move scope option to decorator, and a bug occurs all users have the same things ! (i'm using a  cache in this provider for user related things)

**Comment by ardatan** [comment]
Could you please open an issue instead ?

**Comment by kesslerdev** [comment]
sure !

**Pull request closed without merging**
