### PR TITLE
Support __resolveReference resolver for federation

### PR DESCRIPTION
**Pull request by Albert-Lo**
For issue addressed in https://github.com/Urigo/graphql-modules/issues/1522

### CODE REVIEW

**Comment by dotansimha** [comment]
@kamilkisiela can you please review? Also, do you think it's something we should add to graphql-modules preset in codegen?

**Comment by ardatan** [comment]
Sounds cool! Maybe we need a recipe that explains how to use Modules for federated schema (like adding `buildFederatedSchema` as schema factory function) @Albert-Lo @dotansimha @kamilkisiela

**Comment by ardatan** [comment]
Merging it now! We can add docs later!

**Comment by kamilkisiela** [comment]
[`v1.3.0`](https://github.com/Urigo/graphql-modules/releases/tag/graphql-modules%401.3.0)

**Pull request merged**
