### PR TITLE
test: operation scoped provider should be created once per GraphQL Operation

### PR DESCRIPTION
**Pull request by kamilkisiela**
Related #1295

### CODE REVIEW

**Comment by maapteh** [comment]
Really helpful you pick this stuff up soo quickly, even on a beta. Super helpfull!!!

**Comment by kamilkisiela** [comment]
I will try to release a new beta today, will let you know

**Comment by kamilkisiela** [comment]
@maapteh https://github.com/Urigo/graphql-modules/releases/tag/1.0.0-alpha.2

**Comment by maapteh** [comment]
Will test it now, will also test the middleware since that also seemed to be called more then expected. Super work Kamil!

**Comment by maapteh** [comment]
Awesome! Operation scope and our dataloader is working as before with old session scope. Will also do some loadtests. Thanks for releasing

**Comment by kamilkisiela** [comment]
@maapteh You can check our benchmark https://github.com/Urigo/graphql-modules/pull/1298/checks?check_run_id=1035657605

The `createSchemaForApollo()` wraps every root-level resolver and executes a GraphQL Operation in each so it will be much much slower than using GraphQL Modules with `createExecution()` and passing it to a graphql server.

**Comment by maapteh** [comment]
So should we ask updates on the apollo server PR you created?

**Pull request merged**
