### PR TITLE
Seperate di package

### LINKED ISSUE #183: TypeError: Reflect.hasMetadata is not a function
Using `0.2.0` and examples within documentation, I'm receiving `TypeError: Reflect.hasMetadata is not a function` from `@graphql-modules/core/dist/di/index.js:208:22`

I'm not using any dependency injection, just basic example.

### PR DESCRIPTION
**Pull request by ardatan**
Fixes #183 
`@graphql-modules/di`

### CODE REVIEW

**Comment by alfaproject** [comment]
I'm using TypeDI and was wondering if I need to use two different DI libraries now

**Comment by ardatan** [comment]
@alfaproject You can ignore GraphQL-Modules DI, because it is optional. You can pass your own injector/container in contextBuilder, then use it in your resolvers etc.

**Comment by OLDIN** [comment]
@ardatan How can I integrate typedi library to use my containers in resolvers?
Can you please give an example.
Thank you!

**Comment by ardatan** [comment]
@OLDIN You can pass your TypeDi container inside a `GraphQLModule` and import it wherever you need.

```typescript
import { Container } from 'typedi';
const TypeDIModule = new GraphQLModule({
  context: session => {
    return {
       container: Container.of(session),
    };
  }
})
```

```typescript
const OtherModule = new GraphQLModule({
   imports: [TypeDIModule],
   resolvers: {
        SomeType: {
           someField: (root, args, context, info) => context.container.get(SomeTypeDIService).doSomeStuff()
         }
   }
})
```

**Comment by OLDIN** [comment]
@ardatan Thank you. It's work.

**Pull request closed without merging**
